//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumFixture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumFixture.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse coordinate as &apos;int, int&apos;.
        /// </summary>
        internal static string CoordinateIsNoPair {
            get {
                return ResourceManager.GetString("CoordinateIsNoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge browser can only work with system proxy.
        /// </summary>
        internal static string EdgeNeedsSystemProxy {
            get {
                return ResourceManager.GetString("EdgeNeedsSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer requires a screen scaling of 100%. Set via Control Panel/Display Settings.
        /// </summary>
        internal static string IEScreenScalingIssue {
            get {
                return ResourceManager.GetString("IEScreenScalingIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set a browser before opening a page.
        /// </summary>
        internal static string NoBrowserSpecified {
            get {
                return ResourceManager.GetString("NoBrowserSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop to coordinates was not implemented for web browsers.
        /// </summary>
        internal static string NoDragDropToCoordinates {
            get {
                return ResourceManager.GetString("NoDragDropToCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser or driver does not support web storage.
        /// </summary>
        internal static string NoWebStorage {
            get {
                return ResourceManager.GetString("NoWebStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParser requires a non-null locator.
        /// </summary>
        internal static string NullLocator {
            get {
                return ResourceManager.GetString("NullLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParser requires a non-null search criterion.
        /// </summary>
        internal static string NullSearchCriterion {
            get {
                return ResourceManager.GetString("NullSearchCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be Machine Policies, Machine, User Policies, or User.
        /// </summary>
        internal static string RegistryLocationIssue {
            get {
                return ResourceManager.GetString("RegistryLocationIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse size as &apos;int, int&apos;.
        /// </summary>
        internal static string SizeIsNoPair {
            get {
                return ResourceManager.GetString("SizeIsNoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still stale after retrying.
        /// </summary>
        internal static string StaleAfterRetry {
            get {
                return ResourceManager.GetString("StaleAfterRetry", resourceCulture);
            }
        }
    }
}
